name: TTYD_docker
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - colorama=0.4.6
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - flask=2.2.2
  - flask-cors
  - importlib-metadata=6.8.0
  - importlib_metadata
  - ipykernel=6.25.2
  - ipython=8.16.0
  - itsdangerous=2.0.1
  - jedi=0.19.0
  - jinja2=3.1.2
  - jupyter_client=8.3.1
  - jupyter_core=5.3.2
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.5.6
  - openssl=3.0.11
  - packaging=23.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.2.1
  - platformdirs
  - prompt-toolkit
  - prompt_toolkit=3.0.39
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.16.1
  - python=3.10.13
  - python-dateutil
  - python_abi=3.10=2_cp310
  - pyzmq=23.2.1
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.10.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - wcwidth=0.2.7
  - werkzeug=2.2.3
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - accelerate==0.23.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - aiostream==0.5.1
      - annotated-types==0.5.0
      - anyio==3.7.1
      - appdirs==1.4.4
      - asgiref==3.7.2
      - async-timeout==4.0.3
      - attrs==23.1.0
      - beautifulsoup4==4.12.2
      - bitsandbytes==0.41.1
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - click==8.1.7
      - cloudpickle==2.0.0
      - dataclasses-json==0.6.1
      - datasets==2.14.5
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - fastapi==0.103.2
      - filelock==3.12.4
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gitdb==4.0.10
      - gitpython==3.1.37
      - greenlet==2.0.2
      - grpclib==0.4.3
      - h2==4.1.0
      - hpack==4.0.0
      - huggingface-hub==0.17.3
      - hyperframe==6.0.1
      - idna==3.4
      - ipywidgets==8.1.1
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jupyterlab-widgets==3.0.9
      - langchain==0.0.305
      - langsmith==0.0.41
      - llama-index==0.8.2.post1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - mdurl==0.1.2
      - modal==0.53.3704
      - modal-client==0.50.3044
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - networkx==3.1
      - numexpr==2.8.7
      - numpy==1.26.0
      - openai==0.28.1
      - pandas==2.1.1
      - pathtools==0.1.2
      - peft==0.5.0
      - protobuf==4.24.3
      - pyarrow==13.0.0
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.8.8
      - requests==2.31.0
      - rich==13.5.3
      - safetensors==0.3.3
      - scipy==1.11.3
      - sentry-sdk==1.31.0
      - setproctitle==1.3.2
      - sigtools==4.0.1
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.21
      - starlette==0.27.0
      - sympy==1.12
      - synchronicity==0.5.3
      - tblib==2.0.0
      - tenacity==8.2.3
      - tiktoken==0.5.1
      - tokenizers==0.13.3
      - toml==0.10.2
      - torch==2.0.1
      - tqdm==4.66.1
      - transformers==4.31.0
      - trl==0.7.1
      - typer==0.9.0
      - types-certifi==2021.10.8.3
      - types-toml==0.10.8.7
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - wandb==0.15.11
      - watchfiles==0.20.0
      - widgetsnbextension==4.0.9
      - xxhash==3.3.0
      - yarl==1.9.2
      - flask_socketio
